In [48]:
import pandas as pd
import numpy as np

In [49]:
df = pd.read_csv("athlete_events.csv")

In [50]:
len(df['Name'].unique())

134732

In [51]:
df['gold'] = np.where(df['Medal']=="Gold", 1, 0)
df['silver'] = np.where(df['Medal']=="Silver", 1, 0)
df['bronze'] = np.where(df['Medal']=="Bronze", 1, 0)

In [52]:
medals = df[["NOC","gold","silver","bronze"]]

In [53]:
medals = medals.groupby("NOC").sum().sort_values(by=['gold','silver'],ascending=False)
medals

     gold  silver  bronze
NOC
USA  2638    1641    1358
URS  1082     732     689
GER   745     674     746
GBR   678     739     651
ITA   575     531     531
..    ...     ...     ...
VNM     0       0       0
WIF     0       0       5
YAR     0       0       0
YEM     0       0       0
YMD     0       0       0

[230 rows x 3 columns]

In [56]:
name_map = pd.read_csv("noc_regions.csv")
name_map.set_index("NOC",inplace=True)
medals = pd.concat([name_map, medals], axis=1)

/home/star2/ecf3/anaconda3/envs/hackathon/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until

ValueError: Shape of passed values is (460, 7), indices imply (231, 7)

In [55]:
medals

     bronze  gold                 notes       region  silver
NOC
AFG     NaN   NaN                   NaN  Afghanistan     NaN
AHO     NaN   NaN  Netherlands Antilles      Curacao     NaN
ALB     NaN   NaN                   NaN      Albania     NaN
ALG     NaN   NaN                   NaN      Algeria     NaN
AND     NaN   NaN                   NaN      Andorra     NaN
..      ...   ...                   ...          ...     ...
VNM     0.0   0.0                   NaN          NaN     0.0
WIF     5.0   0.0                   NaN          NaN     0.0
YAR     0.0   0.0                   NaN          NaN     0.0
YEM     0.0   0.0                   NaN          NaN     0.0
YMD     0.0   0.0                   NaN          NaN     0.0

[460 rows x 5 columns]